secrets:
    appKey: ENC[AES256_GCM,data:Ykf+/R1K6lQMrXFbmHLu4akxElTQhSoYeY1E2asLUMXmj+7V4k1Oe98YfBsl1OOQcBDU,iv:u4F83atuokU+rxfpRv2EavD2QV/MDsy4r3sEoULXXOE=,tag:dyurUblFFGyD61oeLPMZIw==,type:str]
sops:
    age:
        - recipient: age1ctfpy39dh3n0tlqtrqsdwsasmq2jc37jyk9trr9uxgqrn8flkunqkwyezd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRGhVMU0rM21ZVjRrTjVU
            VVpkVUNubDV4alZvNWFkOTZzNEZjcGRuekJzCitWTG53b3ZDWjBNMmo5S2g0czBk
            YTJmdlJzM2ZLcjZ1OUN5VXV3U0Y2d0kKLS0tIFk0TzFIV0hMTFl2b2x4RW4xeUJP
            cm05VXFGczE4aW95RWMrbndOZTRBSkEK1uoqAIUSq1gqFbowHte75JiYZjIzoHv6
            IMFps31fLu+OoIQpJBktoT3W9s6wLAT++1MMS1O3GfRQliUrjG/R/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T08:37:57Z"
    mac: ENC[AES256_GCM,data:SMauPsHv61/aeV2ePerseeUOgZEiQpsjjXw8MiovXDebp9t10jqkjyenDll9raoPaIJCCgsYKNgvOExCfghadQR6EnR2RXV4QMAmvHOKh0eZ91KGAmn6GVLlyxj+10cmeFA24+REiK09be6G8fA+EVAXiLIz9slWpwVjo0fro+k=,iv:Byp9Qa5c8KRHPTDAGUNeubUtKdx7a2tbo3ll0kfN714=,tag:s9vx+ZGgIvkWbvJVLXIMoA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
