apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adguard-home.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adguard-home.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
