apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard-home.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    {{- include "adguard-home.selectorLabels" . | nindent 4 }}
