secrets:
    grafanaUser: ENC[AES256_GCM,data:Rh/wAhA=,iv:UkDWZidzoF8vasK+O69Ouc29KxgXvYVpSvPHxJH+w00=,tag:eAK8RwxQs8q/J+cEJFXGNA==,type:str]
    grafanaPassword: ENC[AES256_GCM,data:WEvLHzHb7g==,iv:yIzLYNu41a/i0GEfXIY5meJoY5vUK4U+IwA0f96A7zs=,tag:Mdiw9rfU3rlpDxGDoa7/tQ==,type:str]
sops:
    age:
        - recipient: age1ctfpy39dh3n0tlqtrqsdwsasmq2jc37jyk9trr9uxgqrn8flkunqkwyezd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOak5aTEV1WEFHbDNlWjQ3
            TGJ3cGhaVXZ2UkovNjhES293N3dFNDRGQ1NVCmxMdWdlVzhBMUFMamJENnAxV285
            Q0RZMGZqMkZPUDdTN0RySnlwblVZZ00KLS0tIDUzUkJPUjZ0dHRVMlhxV0VjT2Fz
            c2RYeEg0dnYwU3dXMGtyL2RLRXphekEKBzIEXw5iCBw5pVwJqQr3NHyWnVCEmKNM
            k7if0XlNM8ZqLb06JldZDlsFyBh9BCOyVpJREshA0PrWxwVKdqjd+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T03:17:43Z"
    mac: ENC[AES256_GCM,data:skl5BbLtd5hzL8R8nyFEsduC0xl5PRXYUF7Cgn6UeSCJ9DGwTOU/XyIgP5Ga1rc74ra8K7+vHPCKFCUFYyoUybyglK1G16m+S6mraYHp/ILyDw+X83ZEkDI/QFEuYqZ8c4LftSc3iLa1xxQwWUtAtIFqV2aaPZL4NiGYYX/6w88=,iv:PIv5eZM82STrCv2RdN1MfpjYFbgoeHAG7W13aapN0n0=,tag:8ffdKXZg7SFfMiw8fbwYMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
