secrets:
    grafanaApiKey: ENC[AES256_GCM,data:1yHl3CB41zYSL+5XGYpHsMuMQ4R+JCVqKZqfHydXfrL3m38KP9Bnrq8/ypQB7A==,iv:rUTdVv/L6RgtLy9Gf4bNyq5rSDtGbU/NqGLtvpmpF/E=,tag:+OWcRGHOpIoBK6ncXwHvQQ==,type:str]
sops:
    age:
        - recipient: age1ctfpy39dh3n0tlqtrqsdwsasmq2jc37jyk9trr9uxgqrn8flkunqkwyezd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOak5aTEV1WEFHbDNlWjQ3
            TGJ3cGhaVXZ2UkovNjhES293N3dFNDRGQ1NVCmxMdWdlVzhBMUFMamJENnAxV285
            Q0RZMGZqMkZPUDdTN0RySnlwblVZZ00KLS0tIDUzUkJPUjZ0dHRVMlhxV0VjT2Fz
            c2RYeEg0dnYwU3dXMGtyL2RLRXphekEKBzIEXw5iCBw5pVwJqQr3NHyWnVCEmKNM
            k7if0XlNM8ZqLb06JldZDlsFyBh9BCOyVpJREshA0PrWxwVKdqjd+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T01:21:02Z"
    mac: ENC[AES256_GCM,data:hhz0n2r6EOfcPxlXaaJWxb9Fl3yJ5WIRgu2vp81hmYe0l9KOs/BZGL9gE+00YDCz4Ao5M1+GfoBTsDCdL2sEEaGmTd10bM5wps3/HoOp2w7Fp3l1jqPLIXVxHzxidxSOLV+UXUgDq5xLoQZpT3lu//5KahgQFFttnfB1AJOPC3k=,iv:VA+GKb8z7zlwfZj9ZH2ctMU121IyXPwUWCkJIl5OPVo=,tag:skCf6+/RtVEqJMbVML0tOQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
