apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "code-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 512Mi
    limits.memory: 1Gi
    pods: "5"
