{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: code-server-password
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.secrets.password | quote }}
{{- end }}
