secrets:
    password: ENC[AES256_GCM,data:i9F337yxBg==,iv:DcGR/KTIC0ZLZB3gOLC0auDyrvmsGlebJOOdjc6oA1g=,tag:uCwYfdHndmEFp2MOTCfqag==,type:str]
sops:
    age:
        - recipient: age1ctfpy39dh3n0tlqtrqsdwsasmq2jc37jyk9trr9uxgqrn8flkunqkwyezd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZHBlTndZQThVRmp4OUQ2
            MHBSbVFmVHFtdjJBVk9tcXYrTmZlbG5idVE4Cm1PbW9zVDR3RXZEWWkwbmIyUWdW
            MCt0UzY2UXVmWGRSYzRSWVFVTzFYUWMKLS0tIEVZTUlOd2x2eHBJZ2RHSWlhd1Q3
            andET25qaWtjWnh1TXNIc3ZOTmJheVUKHp6d/H7JTfYO/92UbmipC95TYtNXbvDY
            iAg6LgJyVdXgn4QHMkD1asvRdKi20oAWIwRMuQFYrik/YJKQyDsO3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T01:20:28Z"
    mac: ENC[AES256_GCM,data:Ca8O7upAwxfBFpxl9TdcusXOpsTE8ytd9F+ozzOkmJOlVdUOX7xZ/QSXyZRO64ofX/2sNQ9CmU5T9BsHHkTUhNUdHE3UCcW2d1/OYYRv4//sI76X7AEB6cdbNhqhpMX2eUniqoKHoDByejLGYPaMftoN6NxGCaM9Vo5K1WP7HIA=,iv:Ckv8rFIgJhaXrPxPyk2qAT36iatPhl35V5LBp5JnmXc=,tag:KOaet+YLOFHt9FNwDTSjww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
