secrets:
    encryptionKey: ENC[AES256_GCM,data:Hng3keYO/G4y+am27PGYpG8Zr6uKPa7nmgtCSJ/60m8=,iv:f8LUUP7YomhgMlQALShxpiR31MG9D6Z45l1PixYpWH8=,tag:llAs4HcqHai8Nys4IeAV5A==,type:str]
sops:
    age:
        - recipient: age1ctfpy39dh3n0tlqtrqsdwsasmq2jc37jyk9trr9uxgqrn8flkunqkwyezd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTHZDSW9iM2VvbmdKNTRs
            L0ltd0ZZWlFybGk4WnljcEhRK09UdWV1dnhjCktXYlkyRnJxV2RqUTJRcW5vNGtR
            c0p0czNKWG96a3lTb1Q5UjVwWDNITUUKLS0tIDE4dVpCNXNKOHJOYXBiNG9QT1BF
            eWw2eklQdC9RM0ZPWStXZ05MNWl3dHMK4PJDNduMlpa/XHNwcSpNuC7/h4btoVvN
            wRLKyfW7O9cLra+rxVt4Gw5lvdQWY2ISyI6y7dvws2xACoxpfMPXRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T07:02:46Z"
    mac: ENC[AES256_GCM,data:B3cpmFtutlEfr6Wq31gqIrtX2LprAJjH/WR9okm6byO2mg9ZbUE7oyDLYurrxs3KxnPC4AJwLN4PBH34C3c8iBi8qjjdaM+c1jfNhU7/ntf6rsa9wcBCqqtlOvvPFKEqzKU6oOegSSivQjYWOGt3Cis5XV1wFHm+LhgWqtFO20Y=,iv:esMe5/dX9pfU2B/5RngbiJ76c2TLM1syCO5tzzdNPSg=,tag:QOzZFkWR1BhzrIb8U0IFWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
