secrets:
    encryptionKey: ENC[AES256_GCM,data:LBDb+yjnTeDOq9PJ8Qovbb+Tf0kVZqyfKQAadHCWJwv+AorIDhQfpBCkpk2LiaDGIrTxYEPJSc19+/ligDj/WQ==,iv:H5saRYJqiU/tWZSGpqNff1SbRVtA1IF+e81hMQZLwhY=,tag:6beUsL6hHJqp5u36RdLGCQ==,type:str]
sops:
    age:
        - recipient: age1ctfpy39dh3n0tlqtrqsdwsasmq2jc37jyk9trr9uxgqrn8flkunqkwyezd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQnBsZkRKV1dBL21TeE1u
            c1BnZWFrVnF5RXBDcmt1eTZmdTY3aStvdndzCkNiaDcwaVdwcmJEVlV2bkVjdm9k
            aDh5S1BqeC9QdmtHRjZ1RHRaYStCQTgKLS0tIE9RU0EzVmdPeE5aYUswTCs0RWE1
            RXZVbGxmeXBIVUtyTDA5YUdoZU05RFkKXXwolh210UsVrUQ1t6ukFNqnPiUTRNm7
            aMdUUb68a2jDsI5DGz8qFcb1rGrdFPbihxF3AvjKrZKoOXvdfQr5xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T08:17:17Z"
    mac: ENC[AES256_GCM,data:AC5/BCLqgEBtyVjOWuR/jF5w+ZboSL/c1CJimxUNTnFc3fWEnWkLQfr8WLfcnj1u/VGRAM9eY+cy/LeSvCB4iOaB5vstVolkb3N1UErkxJs/DN6hQi0we4H4b4qR0huHrTs+YF3NVvnGt2ChPn/RQrtUeS1AskeGCZr1fmMz9o8=,iv:WaB05hk3jozP4Fl3uK/GWftgXGzlcbRNwvP3Xnl6TxA=,tag:NWWZeTJMuwXHM8etyQ0kMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
