{{- if .Values.apps.homepage.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/gavxm/homelab.git
    targetRevision: main
    path: {{ .Values.apps.homepage.path }}
    helm:
      valueFiles:
        - values.yaml
        - secrets://secrets.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.apps.homepage.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
