kube-prometheus-stack:
    grafana:
        adminPassword: ENC[AES256_GCM,data:Ka0gHXrrzQ==,iv:4FUPEf68DReEgpNzEq7w+hLC75JeaDWcpX4A/Ol80m4=,tag:u0Nh85sisR27aG0vfh3e0g==,type:str]
secrets:
    discord:
        webhookUrl: ENC[AES256_GCM,data:g+mTpWKyg60kUgQieFVW2uvJHgKJNa2zV12EudKD3bB1nC3L+qoqkuaZQnpVgUPnrL3MKdVMuh6dZ+7fR9HqycMGxVTvwX4a7Cc7W+oQYnkvr5qzBVoO5D8h+ltYXCV/eKXlbN//8GWDaJVsxmuMUlexCWzS4VO0Zw==,iv:g6U+eTZTBLt68TJViCv2rm5JfNpP+2WsRsLgEkou5wY=,tag:gOlEuPA6h5sjHzWVVLTOAQ==,type:str]
sops:
    age:
        - recipient: age1ctfpy39dh3n0tlqtrqsdwsasmq2jc37jyk9trr9uxgqrn8flkunqkwyezd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdDdSWFdGYlFsSHM4UFFp
            K0hUY1VIbFBVNkVyRG9JRS9WQTZwcFlrbDJjCkFvVVowNkorNXBYZjFsbzQvOWNS
            Z0FsbzF5Tm5yRGwzWVZtekV3TkdrWTAKLS0tIDNVMWdHcDhpa1lENWJ6U1NHZGU5
            TFRRNmFvQ2E1MmwxVHBkRktQdDVleFkKcQ6jpzOSHUMcJfDp6qVQqBtu6cbcRcVF
            OZ2r8UEadohOGcl+8gUcgvhGGdGmf0jSgXTCWgEOTX7vHXw4ysHHcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T01:20:00Z"
    mac: ENC[AES256_GCM,data:MoiubGlzMqneadPfIBnk3dzTJTXySRxyW0Crgg1Krq28mlvDWHeQF3J2si8Hv4fiNvjCu6+Ynjcet3Tw5zueGYRpLG2th0vzt2f9nqnc8P6HSIurxCd3xLfNbJtR8u7cM6PH5vzMyGL4+mJ8sjpgd9J8ZmwR6H60Qb77e9pk9bI=,iv:RTKWWrci+O2fjl5ED08KHWFAYmD6T8XjJUNyBiI17gk=,tag:7CRoUD9xhyeegdVvPhBTwg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
