apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "homarr.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    requests.cpu: 200m
    requests.memory: 512Mi
    limits.memory: 1Gi
    pods: "3"
