{{- if .Values.secrets }}
{{- if .Values.secrets.discord }}
apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  url: {{ .Values.secrets.discord.webhookUrl | quote }}
{{- end }}
{{- end }}
