secrets:
    tunnelToken: ENC[AES256_GCM,data:xbrRT3KPuese04wYaQOlh6JtIcPCN3PS1svewD4tNpbN+cPQ6WYB3GaMylKVeghmwPTqnSAv2Y6mjvzFoDtphi+vfwsUepChoQLdVrkdtHUr+pa1zKg3j5OqHLxfoKSskRITNuKjVHoPpLmmftn6ofrOKyzKfH4JWUeKE074PkDOk5xHBaAzcgTZsv6cQH4+sQAwlAMcgo6hyRL8Y8srMKnM10sQmv2KB1LP0Ny/+0YQXlUnI9eqSQ==,iv:h5qdYCE0IoDWbDd15L3OnLSw+eDQzz/f8TtqUMwpnOo=,tag:tlC5KbLg6rs9F2VVJqYKPQ==,type:str]
sops:
    age:
        - recipient: age1ctfpy39dh3n0tlqtrqsdwsasmq2jc37jyk9trr9uxgqrn8flkunqkwyezd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSTZIMHVwa3VVbG1pTjVP
            MWRERGcrbGRQYkZ6ZGg2OGowTkFWZjEwMmlrCm94dFlHRG5LT1NOM25VTUs2WjVB
            Ung0Z0tLU2g5WDBuc1p2R1lnbGRzWFkKLS0tIEJ2YWVtZTh5T1YvK0JSWGI0QnBY
            RWx1UWUyaEx0ejhOaXNzRDN4YjBOOFkKPvWkIFlYRk27Gn9vaNnx/xwTTVvHufrD
            /8hJ5Ifvb1I8TirO4mO5sNeSBvkd0ZogH5HCXp9uo8wUeHZQHbLJvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T06:26:45Z"
    mac: ENC[AES256_GCM,data:ULWchonBxBZQgR4+dBTR5xo/JWOvp9U6HtOE9jXShqssFsCUd5d2boq60kC6j2vQEZZHgOO+XQn1DbQqOsWNc8AfcWJlrxNlp0ZJDreH0IQFNgE/rKetY49GokeGlvcAplV8qE3NDGoihza/1hd61hpZmBanAn+I1AZGEieb1J4=,iv:iowkHjH6ULQDRIxoSN4vSJvHV+fUFL/BrtUZkkxLAyQ=,tag:3UBa6sjZ18GtAnvzrgbq1Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
