apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "speedtest-tracker.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    requests.cpu: 200m
    requests.memory: 256Mi
    limits.memory: 512Mi
    pods: "3"
