apps:
  argocd:
    enabled: true
    namespace: argocd
    path: charts/argocd
  homepage:
    enabled: true
    namespace: homepage
    path: charts/homepage
  uptime-kuma:
    enabled: true
    namespace: uptime-kuma
    path: charts/uptime-kuma
  monitoring:
    enabled: true
    namespace: monitoring
    path: charts/monitoring
  logging:
    enabled: true
    namespace: logging
    path: charts/logging
  code-server:
    enabled: true
    namespace: code-server
    path: charts/code-server
  cloudflared:
    enabled: true
    namespace: cloudflared
    path: charts/cloudflared
  certManager:
    enabled: true
    namespace: cert-manager
    path: charts/cert-manager
