apps:
  homepage:
    enabled: true
    namespace: homepage
    path: charts/homepage
  uptime-kuma:
    enabled: true
    namespace: uptime-kuma
    path: charts/uptime-kuma
  monitoring:
    enabled: true
    namespace: monitoring
    path: charts/monitoring
  logging:
    enabled: true
    namespace: logging
    path: charts/logging
