apps:
  argocd:
    enabled: true
    namespace: argocd
    path: charts/argocd
  homepage:
    enabled: false
    namespace: homepage
    path: charts/homepage
  uptime-kuma:
    enabled: true
    namespace: uptime-kuma
    path: charts/uptime-kuma
  monitoring:
    enabled: true
    namespace: monitoring
    path: charts/monitoring
  logging:
    enabled: true
    namespace: logging
    path: charts/logging
  code-server:
    enabled: true
    namespace: code-server
    path: charts/code-server
  cloudflared:
    enabled: true
    namespace: cloudflared
    path: charts/cloudflared
  certManager:
    enabled: true
    namespace: cert-manager
    path: charts/cert-manager
  adguardHome:
    enabled: true
    namespace: adguard-home
    path: charts/adguard-home
  itTools:
    enabled: true
    namespace: it-tools
    path: charts/it-tools
  speedtestTracker:
    enabled: true
    namespace: speedtest-tracker
    path: charts/speedtest-tracker
  homarr:
    enabled: true
    namespace: homarr
    path: charts/homarr
