{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "homepage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ include "homepage.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "homepage.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
