{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: homepage-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
type: Opaque
stringData:
  grafana-api-key: {{ .Values.secrets.grafanaApiKey | quote }}
{{- end }}
