{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: homepage-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
type: Opaque
stringData:
  grafana-user: {{ .Values.secrets.grafanaUser | quote }}
  grafana-password: {{ .Values.secrets.grafanaPassword | quote }}
{{- end }}
