{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.secrets.tunnelToken | quote }}
{{- end }}
